# Generated by Django 2.0.6 on 2018-06-09 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('AID', models.IntegerField(primary_key=True, serialize=False)),
                ('StartTime', models.IntegerField()),
                ('EndTime', models.IntegerField()),
                ('StartDate', models.CharField(max_length=20)),
                ('Status', models.IntegerField()),
                ('BookDate', models.CharField(max_length=20)),
                ('Statement', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('CID', models.IntegerField(primary_key=True, serialize=False)),
                ('RoomName', models.CharField(max_length=5)),
                ('Capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomOccupied',
            fields=[
                ('OID', models.IntegerField(primary_key=True, serialize=False)),
                ('Date', models.CharField(max_length=20)),
                ('Time', models.IntegerField()),
                ('CID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UID', models.IntegerField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('IsStudent', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='CID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Classroom'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='UID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.User'),
        ),
    ]
