# Generated by Django 2.0.6 on 2018-06-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Statement',
            new_name='Usage',
        ),
        migrations.AddField(
            model_name='classroomoccupied',
            name='Usage',
            field=models.CharField(default='abc', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Status',
            field=models.IntegerField(choices=[(0, '审批中'), (1, '已通过'), (2, '未通过')]),
        ),
    ]
