# Generated by Django 2.0.6 on 2018-06-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20180610_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Reason',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='classroomoccupied',
            name='Usage',
            field=models.CharField(default='', max_length=20),
        ),
    ]
